server:
  tomcat:
    max-http-post-size: -1
spring:
  jmx:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  # 文件上传大小
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 指定激活配置
  profiles:
    active: prod
    include: process
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池的最小维持连接数
    minIdle: 5
    # 初始化连接数
    initialSize: 5
    # 最大连接数
    maxActive: 20
    # 等待连接获取的最大超时时间
    maxWait: 60000
  redis:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间
    timeout: 5000
#  flyway:
#    table:
#
mabatis:
  #配置mapper xml 文件所在的路径
  mapper-locations: classpath*:com/shop/system/domain/mapper/*.xml
  #配置映射类所在的包名
  type-aloases-package: com/shop/system/domain

aizzbcache:
  type: redis
