#  线上配置文件
server:
  port: 9099
spring:
  datasource:
    # 数据库url
    url: jdbc:mysql://127.0.0.1:3306/cece?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
logging:
  config: classpath:logback/logback.cfg.prod.xml
